### ISSUE TITLE
Version 2.0.1 not available in marketplace

### ISSUE THREAD

**Issue by himpierre** [RedOne-Guerad/rc-auto-reply#5]
Hello!

Thanks for this wonderful app! May I ask for the reason version 2.0.1 is not available from the rocketchat marketplace?

cheers!

**Comment by RedOne-Guerad** [comment]
Hi @himpierre thank you for your feedback!
version 2.0.1 was submitted to rocketchat marketplace long ago, but unfortunately rocketchat team still did not review it yet 😔
i hope they will approve it soon  🙏

**Comment by himpierre** [comment]
Thanks for your answer! I was planning to switch to your app but was concerned about its state of maintenance. Alright then, will move forward.

cheers!

Am 19. September 2024 19:47:55 MESZ schrieb Redouane GUERAD ***@***.***>:
>Hi @himpierre thank you for your feedback!
>version 2.0.1 was submitted to rocketchat marketplace long ago, but unfortunately rocketchat team still did not review it yet 😔
>i hope they will approve it soon  🙏
>

**Comment by RedOne-Guerad** [comment]
> Thanks for your answer! I was planning to switch to your app but was concerned about its state of maintenance. Alright then, will move forward. cheers! Am 19. September 2024 19:47:55 MESZ schrieb Redouane GUERAD ***@***.***>:

I highly recommend switching :rocket: 
the app is actively maintained, and if you encounter any problems or have ideas for improvements, please don't hesitate to submit an issue or even a pull request!

**Comment by mvvvmd** [comment]
@RedOne-Guerad FYI I got the RC team to update the app in the Marketplace from v1.0 to 2.0.1.

**Comment by himpierre** [comment]
Yay! Thanks!

Am 19. November 2024 08:20:00 MEZ schrieb Machiel van Veen ***@***.***>:
>@RedOne-Guerad FYI I got RC to update the app in the Marketplace from v1.0 to 2.0.1.
>

**Comment by RedOne-Guerad** [comment]
> @RedOne-Guerad FYI I got the RC team to update the app in the Marketplace from v1.0 to 2.0.1.

Yes, version 2.0.1 is available in RC marketplace since 18-11-2024
